# Generated by Django 4.2.5 on 2023-10-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_alter_recipe_tags_alter_recipestep_recipe'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shopping_list',
            field=models.ManyToManyField(to='recipe.ingredient'),
        ),
    ]
